{% set name = "opentelemetry-instrumentation-pymongo" %}
{% set version = "0.32b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-pymongo-{{ version }}.tar.gz
  sha256: 6720f209d0a2578804b46e3f7385f292eecfb2cd090a8edf0d3696c3b83aee9a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.32b0
    - opentelemetry-semantic-conventions ==0.32b0
    - python >=3.6
    # - pymongo ~=3.1
    # - opentelemetry-test ==0.24b0
    # - pymongo ~=3.1
    # - opentelemetry-test ==0.25b0
    # - pymongo ~=3.1
    # - opentelemetry-test ==0.25b2
    # - pymongo ~=3.1
    # - opentelemetry-test-utils ==0.26b1
    # - pymongo ~=3.1
    # - opentelemetry-test-utils ==0.27b0
    # - pymongo ~=3.1
    # - opentelemetry-test-utils ==0.28b0
    # - pymongo ~=3.1
    # - opentelemetry-test-utils ==0.28b1
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.29b0
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.30b0
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.30b1
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.31b0
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.32b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-pymongo
  summary: OpenTelemetry pymongo instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
